import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Product',
      items: [{ type: 'autogenerated', dirName: 'product' }],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Security',
      items: [{ type: 'autogenerated', dirName: 'security' }],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [{ type: 'autogenerated', dirName: 'adr' }],
    },
    {
      type: 'category',
      label: 'Planning',
      items: [{ type: 'autogenerated', dirName: 'planning' }],
    },
  ],
};

export default sidebars;
